[build]
  publish = "build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.herokuapp.com/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false"