[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-app.herokuapp.com/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
